let currentSong = 0;
let songs = [
  ['songs/Canon_in_D.mid', 'Canon in A'],
  ['songs/Canon_in_D.mid', 'Canon in B'],
  ['songs/Canon_in_D.mid', 'Canon in C'],
  ['songs/Canon_in_D.mid', 'Canon in D'],
  ['songs/Canon_in_D.mid', 'Canon in E'],
  ['songs/Canon_in_D.mid', 'Canon in F'],
  ['songs/Canon_in_D.mid', 'Canon in G'],

  ['songs/Canon_in_D.mid', 'Canon in A'],
  ['songs/Canon_in_D.mid', 'Canon in B'],
  ['songs/Canon_in_D.mid', 'Canon in C'],
  ['songs/Canon_in_D.mid', 'Canon in D'],
  ['songs/Canon_in_D.mid', 'Canon in E'],
  ['songs/Canon_in_D.mid', 'Canon in F'],
  ['songs/Canon_in_D.mid', 'Canon in G'],

  ['songs/Canon_in_D.mid', 'Canon in A'],
  ['songs/Canon_in_D.mid', 'Canon in B'],
  ['songs/Canon_in_D.mid', 'Canon in C'],
  ['songs/Canon_in_D.mid', 'Canon in D'],
  ['songs/Canon_in_D.mid', 'Canon in E'],
  ['songs/Canon_in_D.mid', 'Canon in F'],
  ['songs/Canon_in_D.mid', 'Canon in G'],

  ['songs/Canon_in_D.mid', 'Canon in A'],
  ['songs/Canon_in_D.mid', 'Canon in B'],
  ['songs/Canon_in_D.mid', 'Canon in C'],
  ['songs/Canon_in_D.mid', 'Canon in D'],
  ['songs/Canon_in_D.mid', 'Canon in E'],
  ['songs/Canon_in_D.mid', 'Canon in F'],
  ['songs/Canon_in_D.mid', 'Canon in G'],

  ['songs/Canon_in_D.mid', 'Canon in Al'],
  ['songs/Canon_in_D.mid', 'Canon in Bl'],
  ['songs/Canon_in_D.mid', 'Canon in Cl'],
  ['songs/Canon_in_D.mid', 'Canon in Dl'],
  ['songs/Canon_in_D.mid', 'Canon in El'],
  ['songs/Canon_in_D.mid', 'Canon in Fl'],
  ['songs/Canon_in_D.mid', 'Canon in Gl'],
];
